# apiVersion: v1
# kind: configmap
# matadata:
#   name: backend
#   namespace: expense
# data:
#  DB_HOST: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: expense # if namespace was not provided it will take the default namespace.
  labels: # these are the replicaset lables.
     tier: web
     app: frontend
     project: expense
spec:
  replicas: 2
  selector: 
  matchLabels:
       tier: web
       app: frontend
       project: expense
  template: 
    metadata:
      labels:
       tier: web
       app: frontend
       project: expense
    spec:
      containers:
      - name: frontend
        image: raidi/backend:v1
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          # limits is greater than or equal to requests
          limits:
            cpu: 100m
            memory: 128Mi
        
---
apiVersion : v1
kind: Service
metadata:
  name: frontend
  namespace: expese
spec:
  type: LoadBalancer
  selector:
    tier: api
    app: frontend
    project: expense
  ports:
   - name: frontend-port
     protocol: TCP
     port: 80 # service port
     targetPort: 80 #container port


#ctl get pods -n expense ---> (if -n is not given it will take defacult namespace)