apiVersion: v1
kind: ConfigMap
metadata:
  name: backend
  namespace: expense
data:
  DB_HOST: mysql
---
apiVersion: app/v1
kind: deployment
metadata:
  name: backend
  labels: 
    app: nginix
    tier: backend
spec:
  replicas: 3
  selector: 
  matchLabels:
      tier: backend
      app: nginx
  template: 
    metadata:
      labels:
        tier: backend
        app: nginx
    spec:
      containers:
      - name: nginx
        image: raidi/backend:v1
---
apiVersion : v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    tier: backend
    app: nginx
  ports:
  - name: nginx-svc-port
    protocol: TCP
    port: 8080 # service port
    targetPort: 8080 #container port









