apiVersion: v1
kind: ConfigMap
metadata:
  name: backend
  namespace: expense
  labels:
    app: backend
data:
  DB_HOST: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  labels:
    project: expense
    environment: dev
    created_by: raidi
    module: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      project: expense
      environment: dev
      created_by: raidi
      module: backend
  template:
    metadata:
      labels:
        project: expense
        environment: dev
        created_by: raidi
        module: backend
    spec:
    #initcontainers 
      initContainers:
      - name: mysql-check
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup mysql; do echo waiting for myservice; sleep 2; done"]
      containers:
        - name: backend
          image: raidi/backend:v1
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 120Mi
            limits:
              cpu: 100m
              memory: 120Mi
          envFrom:
          - configMapRef:
              name: backend
            # health check
            readinessProbe:
              tcpSocket:
                port: 8080
              initialDelaySeconds: 15
              periodSeconds: 10
            livenessProbe:
              httpGet:
                path: /health
                port: 8080
              initialDelaySeconds: 3
              periodSeconds: 3 
---
kind: Service
apiVersion: v1
metadata:
  name: backend
  namespace: expense
spec:
  selector:
    project: expense
    environment: dev
    created_by: raidi
    module: backend
  # type: ClusterIP
  ports:
    - name: backend
      protocol: TCP
      port: 8080
      targetPort: 8080
---
#HPA
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: backend
 namespace: expense
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: backend
 minReplicas: 1
 maxReplicas: 10
 targetCPUUtilizationPercentage: 15 # usually 75 in real environment