apiVersion: v1
kind: configmap
matadata:
  name: backend
  namespace: expense
data:
 DB_HOST: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense # if namespace was not provided it will take the default namespace.
  labels: # these are the replicaset lables.
     tier: api
     app: backend
     project: expense
spec:
  replicas: 2
  selector: 
  matchLabels:
      tier: api
      app: backend
      project: expense
  template: 
    metadata:
      labels:
        tier: api
        app: backend
        project: expense
    spec:
      containers:
      - name: backend
        image: raidi/backend:v1
        envFrom: 
        - configMapRef:
            name: backend
---
apiVersion : v1
kind: Service
metadata:
  name: backend
  namespace: expese
spec:
  selector:
    tier: api
    app: backend
    project: expense
  ports:
   - name: backend-port
     protocol: TCP
     port: 8080 # service port
     targetPort: 8080 #container port


#ctl get pods -n expense ---> (if -n is not given it will take defacult namespace)